Tests for logout controller
rj13371/fun-kickoff-project pull request #3
Opened 2022-01-05 08:34 UTC by rj13371

### What this PR does (required):
made ping test for logout controller to see if it returns a 200 status code

### Any information needed to test this feature (required):

Made Readme in server/README.md

2022-01-05 21:08 UTC, moffatethan approved these changes
Good work!

2022-01-05 21:09 UTC, moffatethan requested changes
Forgot to mention, please base the branch properly. 

[Read how to change the base here](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-the-base-branch-of-a-pull-request)

2022-01-05 21:11 UTC, moffatethan requested changes

2022-01-05 21:11 UTC, moffatethan commented on server/test/ping.spec.js
> +  var url = "http://localhost:3001/auth/logout/"
I would prefer a `const` being used here just for convention in the overall project.

2022-01-05 21:11 UTC, moffatethan commented on server/test/ping.spec.js
> +  var url = "http://localhost:3001/profiles/profiles"
I would prefer a const being used here just for convention in the overall project.

2022-01-05 21:11 UTC, moffatethan commented on server/test/ping.spec.js
> +var request = require('request');
`const` can be used here too. Thanks!

2022-01-06 03:48 UTC, rj13371 commented
I changed the base to profile_controllers here, which is what I worked on before working on this branch. Is this supposed to be based on what I was working on before?

2022-01-06 18:17 UTC, moffatethan commented
> I changed the base to profile_controllers here, which is what I worked on before working on this branch. Is this supposed to be based on what I was working on before?

Yes, exactly 👍🏻 💯

2022-01-06 18:17 UTC, moffatethan approved these changes

2022-01-09 10:57 UTC, merged